name: Lint and Auto-Fix Code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Prevents conflicts with manual authentication

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          npm install --save-dev eslint stylelint stylelint-config-standard htmlhint
          pip install flake8 autopep8

      - name: Run ESLint (JavaScript)
        run: npx eslint . --fix || true

      - name: Run Stylelint (CSS)
        run: npx stylelint "**/*.css" --fix || true

      - name: Run HTMLHint (HTML)
        run: npx htmlhint "**/*.html" --config .htmlhintrc || true

      - name: Run Flake8 (Python)
        run: flake8 . || true

      - name: Auto-Fix Python Code with autopep8
        run: autopep8 --in-place --aggressive --aggressive -r .

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Using GitHub Token for authentication
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "chore: auto-fix linting issues" || exit 0
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
